spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME:campuslab_bookings}
    driver-class-name: org.postgresql.Driver
    username: campuslab
    password: campuslab
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

campuslab:
  catalog:
    base-url: http://ms-campuslab-catalog:8081
