server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: ms-campuslab-notify

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual # ACK/NACK explícitos
        retry:
          enabled: true
          max-attempts: 3