server:
  port: 8083

spring:
  application:
    name: ms-campuslab-audit
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:campuslab}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:campuslab}
    password: ${DB_PASSWORD:campuslab}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: campuslab-audit-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

campuslab:
  kafka:
    topics:
      booking-events: booking-events-topic
