server:
  port: 8083

spring:
  application:
    name: ms-campuslab-audit
  datasource:
    url: jdbc:h2:mem:auditdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: campuslab-audit-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

campuslab:
  kafka:
    topics:
      booking-events: booking-events-topic
