server:
  port: 8082

spring:
  application:
    name: ms-campuslab-bookings

  # Base de Datos H2
  datasource:
    url: jdbc:h2:mem:bookingsdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  # Configuración de Kafka (Broker local)
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # Configuración de RabbitMQ (Broker local)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Propiedades personalizadas requeridas por la aplicación
campuslab:
  rabbitmq:
    exchanges:
      direct: booking.direct.exchange
      topic: booking.topic.exchange
      dlx: booking.dlx.exchange
  kafka:
    topics:
      booking-events: booking-events-topic