server:
  port: 8081

spring:
  application:
    name: ms-campuslab-bookings

  datasource:
    url: jdbc:postgresql://localhost:5432/pedidos360
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuración RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Configuración Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

campuslab:
  rabbitmq:
    exchanges:
      direct: cmd.direct
      topic: cmd.topic
      dlx: cmd.dead.dlx
  kafka:
    topics:
      booking-events: bookings.events
      audit-timeline: audit.timeline