server:
  port: 8082
spring:
  application:
    name: ms-campuslab-bookings
  datasource:
    url: jdbc:h2:mem:bookingsdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true