server:
  port: 8081

spring:
  application:
    name: ms-campuslab-catalog
  datasource:
    url: jdbc:h2:file:./data/catalogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

campuslab:
  rabbitmq:
    exchanges:
      direct: catalog.direct.exchange
      topic: catalog.topic.exchange
      dlx: catalog.dlx.exchange
  kafka:
    topics:
      catalog-events: catalog-events-topic
